# Generated by Django 5.2.12 on 2026-04-02 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costs', '0001_initial'),
        ('projects', '0001_initial'),
        ('tenant_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costentry',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='costentry',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenant_manager.tenant'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenant_manager.tenant'),
        ),
        migrations.AddField(
            model_name='labortype',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenant_manager.tenant'),
        ),
    ]
