# Generated by Django 5.2.12 on 2026-04-02 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0003_remove_costentry_reference_id_costentry_entered_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='costentry',
            old_name='entered_by',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='costentry',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_cost_entry', to=settings.AUTH_USER_MODEL),
        ),
    ]
