# Generated by Django 5.2.12 on 2026-04-02 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('projects', '0001_initial'),
        ('tenant_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='projects.project'),
        ),
        migrations.AddField(
            model_name='location',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenant_manager.tenant'),
        ),
        migrations.AddField(
            model_name='stock',
            name='item_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.itemvariant'),
        ),
        migrations.AddField(
            model_name='stock',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location'),
        ),
        migrations.AddField(
            model_name='stock',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenant_manager.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='itemvariant',
            unique_together={('tenant', 'sku')},
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('item_variant', 'location')},
        ),
    ]
