# Generated by Django 5.2.12 on 2026-04-05 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='total_available',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
