# Generated by Django 5.2.12 on 2026-04-06 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stock_total_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='total_available',
        ),
    ]
