# Generated by Django 5.2.12 on 2026-04-02 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_site_projectstage_site'),
        ('transactions', '0002_inventorytransaction_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.site'),
        ),
    ]
