# Generated by Django 5.2.12 on 2026-04-03 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_materialrequestitem_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialrequestitem',
            name='requested_by',
        ),
    ]
