# Generated by Django 5.2.12 on 2026-04-09 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_incomingstock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialrequest',
            options={'permissions': [('approve_materialrequest', 'Can approve material request')]},
        ),
    ]
