# Generated by Django 5.2.12 on 2026-04-10 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_materialrequest_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='request_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.materialrequest'),
        ),
        migrations.AlterModelOptions(
            name='materialrequest',
            options={},
        ),
        migrations.RemoveField(
            model_name='inventorytransaction',
            name='to_location',
        ),
        migrations.RemoveField(
            model_name='materialrequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='materialrequest',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='materialrequest',
            name='status',
        ),
        migrations.DeleteModel(
            name='MaterialRequestItem',
        ),
    ]
