# Generated by Django 5.2.12 on 2026-04-13 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_item_name'),
        ('transactions', '0011_alter_materialrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.location'),
            preserve_default=False,
        ),
    ]
