# Generated by Django 5.2.12 on 2026-04-02 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('projects', '0001_initial'),
        ('tenant_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='projects.project')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenant_manager.tenant')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('tenant', 'project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StageMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('item_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.itemvariant')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='projects.projectstage')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenant_manager.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'stage', 'item_variant')},
            },
        ),
    ]
