# Generated by Django 5.2.12 on 2026-04-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectstage_stagematerial'),
        ('tenant_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectstage',
            unique_together={('tenant', 'project', 'order')},
        ),
        migrations.AddField(
            model_name='projectstage',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstage',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstage',
            name='status',
            field=models.CharField(choices=[('PLANNING', 'Planning'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold'), ('CANCELLED', 'Cancelled')], default='PLANNING', max_length=20),
        ),
    ]
