# Generated by Django 5.2.12 on 2026-04-07 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_updated_by_site_created_by_site_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='location',
        ),
    ]
